# obraz ubuntu:24.04 z Javą w wersji 8 oraz Kotlinem
# do powyższego należy dodać najnowszego Gradle’a oraz paczkę JDBC
# SQLite w ramach projektu na Gradle (build.gradle)

# uwaga: To nie zadziała, bo najnowszy Gradle nie jest kompatybilny z java8
# FAILURE: Build failed with an exception.
#
#* What went wrong:
# Gradle requires JVM 17 or later to run. Your build is currently configured to use JVM 8.

FROM ubuntu:24.04

RUN apt update \ 
&& apt-get install -y openjdk-8-jre 

RUN apt-get install -y curl zip unzip \ 
&& curl -s "https://get.sdkman.io" | bash \ 
&& bash -c "source $HOME/.sdkman/bin/sdkman-init.sh \
&& sdk install kotlin \
&& sdk install gradle"

COPY . /app

WORKDIR /app

ENTRYPOINT [ "/bin/bash" ]