# stworzyć przykład typu HelloWorld oraz uruchomienie aplikacji
# przez CMD oraz gradle

# doinstalowalem jave 17 z powodu braku kompatybilnosci gradle z 8.

FROM ubuntu:24.04

# jesli gradle ma to uruchomic to jdk a nie jre
RUN apt update \ 
&& apt-get install -y openjdk-17-jdk 

RUN apt-get install -y curl zip unzip \ 
&& curl -s "https://get.sdkman.io" | bash \ 
&& bash -c "source $HOME/.sdkman/bin/sdkman-init.sh \
&& sdk install kotlin \
&& sdk install gradle"

# potrzebne zeby cmd gradle run zadzialal; sdk instaluje w folderze .sdk; wewnatrz kontenera dziala
ENV PATH="/root/.sdkman/candidates/gradle/current/bin:/root/.sdkman/candidates/kotlin/current/bin:${PATH}"

COPY . /app

WORKDIR /app

CMD ["gradle", "run"]