# obraz ubuntu:24.04 z Javą w wersji 8 oraz Kotlinem
FROM ubuntu:24.04

RUN apt update \ 
&& apt-get install -y openjdk-8-jre 

RUN apt-get install -y curl zip unzip \ 
&& curl -s "https://get.sdkman.io" | bash \ 
&& bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install kotlin"

ENTRYPOINT [ "/bin/bash" ]