# 3.0 obraz ubuntu z Pythonem w wersji 3.10
FROM ubuntu:22.04

# why is this hack needed, python?? 
RUN apt-get update \ 
&& apt-get install -y software-properties-common \
&& add-apt-repository ppa:deadsnakes/ppa \
&& apt-get update \
&& apt-get install -y python3.10

ENTRYPOINT [ "/bin/bash" ]